done
devblogs-ir/MicroWebFramework pull request #4
Opened 2023-12-29 18:35 UTC by smjebelli

In this sample implementatino, an HttpListner is listening to the port 3998 on localhost.
there are 2 sample controllers: User and Order. Each controller has 2 actions called GetAll and GetById which GetAll has not inputs but GetById can take an Id as input.
Here are sample http calls:
```sh
http://localhost:3998/Order/GetAll
http://localhost:3998/Order/GetById/2
http://localhost:3998/User/GetAll
http://localhost:3998/User/GetById/4
```

2023-12-30 12:29 UTC, mohammadKarimi requested changes

2023-12-30 12:29 UTC, mohammadKarimi commented on sources/MohammadJebelli/PipelineDesignPattern/AuthenticaionPipe.cs
> +namespace PipelineDesignPattern
File Scoped namespace.

2023-12-30 12:29 UTC, mohammadKarimi commented on sources/MohammadJebelli/PipelineDesignPattern/EndPointPipe.cs
> +
don't use useless line break. 
you have many line break.

2023-12-30 12:29 UTC, mohammadKarimi commented on sources/MohammadJebelli/PipelineDesignPattern/EndPointPipe.cs
> +            if (actionParams.Length != requestParameters.Count())
pattern matching.

2023-12-30 12:29 UTC, mohammadKarimi commented on sources/MohammadJebelli/PipelineDesignPattern/HttpContext.cs
> +        public string httpRequest { get; set; }
pascal naming.

2023-12-30 12:29 UTC, mohammadKarimi commented on sources/MohammadJebelli/PipelineDesignPattern/PipeBuilder.cs
> +        private List<Type> pipes = new List<Type>();
naming convention.
private fields must be started with _

2023-12-30 12:29 UTC, mohammadKarimi commented on sources/MohammadJebelli/PipelineDesignPattern/PipeBuilder.cs
> +        public Action<HttpContext> Build()
this method can be return null. so, you should notify users whenever they are using this method.

2023-12-30 12:29 UTC, mohammadKarimi commented on sources/MohammadJebelli/PipelineDesignPattern/Program.cs
> +while (true)
we dont need this infinity loop/

2023-12-30 12:29 UTC, mohammadKarimi commented on sources/MohammadJebelli/PipelineDesignPattern/Program.cs
> +        context.Response.StatusCode = 404;
avoid using magic numbers. use enums.

2023-12-30 12:29 UTC, mohammadKarimi commented on sources/MohammadJebelli/PipelineDesignPattern/Program.cs
> +    if (requestUrl.Contains("favicon.ico"))
magic string.

2023-12-30 15:46 UTC, smjebelli commented on sources/MohammadJebelli/PipelineDesignPattern/PipeBuilder.cs
> +        public Action<HttpContext> Build()
Thanks for your comment. I changed the Build() method to return nullable Action and while calling it I do a null check for the returned value. Is that what you meant?

2023-12-30 16:16 UTC, smjebelli commented on sources/MohammadJebelli/PipelineDesignPattern/Program.cs
> +while (true)
Actually I think this loop is unavoidable, because after one request the code block finishes and program ends.

2023-12-30 17:31 UTC, smjebelli commented
Thanks for your comments dear Mohammad, I made the changes.
Please check it out again.

2023-12-30 17:53 UTC, mohammadKarimi commented
> Thanks for your comments dear Mohammad, I made the changes. Please check it out again.

If you want to have a review again, please consider that you must change the label to Ready to review. 
thanks. now, I will change it.

2023-12-30 18:01 UTC, mohammadKarimi requested changes

2023-12-30 18:01 UTC, mohammadKarimi commented on sources/MohammadJebelli/PipelineDesignPattern/Program.cs
> +Console.ReadKey();
these two lines, I think both of them is useless. 
because you have written an infinity loop before.

2023-12-30 18:01 UTC, mohammadKarimi commented on sources/MohammadJebelli/PipelineDesignPattern/Utility.cs
> +        if (str == null)
pattern matching.

2023-12-30 18:01 UTC, mohammadKarimi commented on sources/MohammadJebelli/PipelineDesignPattern/Utility.cs
> +    public static string FirstLetterToUpper(this string str)
naming convention, what is str?

2023-12-30 18:01 UTC, mohammadKarimi commented on sources/MohammadJebelli/PipelineDesignPattern/Utility.cs
> +    public const string FAVICON = "favicon.ico";
👍

2023-12-30 18:01 UTC, mohammadKarimi commented on sources/MohammadJebelli/PipelineDesignPattern/Utility.cs
> +    public const string FAVICON = "favicon.ico";
why is it public ?

2023-12-30 18:01 UTC, mohammadKarimi commented on sources/MohammadJebelli/PipelineDesignPattern/Utility.cs
> +            return char.ToUpper(str[0]) + str.Substring(1);
you can use range, index and collection expression ( spread element)

2023-12-31 04:35 UTC, smjebelli commented on sources/MohammadJebelli/PipelineDesignPattern/EndPointPipe.cs
> +
I had an assumption that line breaks makes code more readable, But I think you are right and these line breaks are too much and annoying. Issue fixed. 👍

2023-12-31 04:36 UTC, smjebelli commented on sources/MohammadJebelli/PipelineDesignPattern/Pipe.cs
> +    public abstract void Handle(HttpContext httpContext);
Excuse me, I didn't understand you point.

2023-12-31 04:48 UTC, smjebelli commented on sources/MohammadJebelli/PipelineDesignPattern/Utility.cs
> +    public const string FAVICON = "favicon.ico";
I moved FAVICON varaibale definition to the program.cs file.

2023-12-31 10:16 UTC, mohammadKarimi approved these changes
I will merge your code, but consider there are some issues which remains without any answers. 
Please fix them in next practice.

2023-12-31 10:16 UTC, mohammadKarimi commented on sources/MohammadJebelli/PipelineDesignPattern/PipeBuilder.cs
> +    public PipeBuilder AddPipe<TType>()
there is still no where T : .....

2023-12-31 10:16 UTC, mohammadKarimi commented on sources/MohammadJebelli/PipelineDesignPattern/UserController.cs
> +    private readonly HttpContext _context;
DRY.

please move it into base class.

2023-12-31 10:16 UTC, merged