Feat/niloufar mont
devblogs-ir/MicroWebFramework pull request #6
Opened 2023-12-30 12:47 UTC by lilmont

A httpListenere that listens for requests and runs them through a pipleline with three pipes that routes urls semi-dynamically and handles exceptions and authentication.

**You can try these URLs like:**
http://localhost:7776/Products/GetAllProducts
http://localhost:7776/Products/GetUserById/{id}
http://localhost:7776/Orders/GetAllOrders
http://localhost:7776/Orders/GetOrderById/{id}

2023-12-30 13:19 UTC, thisisnabi requested changes

2023-12-30 13:19 UTC, thisisnabi commented on sources/Niloo Mont/MicroWebFramework/AuthenticationPipe.cs
> +        context.Response.OutputStream.Write(
Why do you write on the output?

2023-12-30 13:19 UTC, thisisnabi commented on sources/Niloo Mont/MicroWebFramework/EncodingService.cs
> +        Encoding.UTF8.GetBytes(input+"\n");
don't abuse the content.

 remove `\n`!

2023-12-30 13:19 UTC, thisisnabi commented on sources/Niloo Mont/README.md
Thanks, it's good.

2023-12-30 13:21 UTC, thisisnabi commented
Please do not choose 2 reviewers! @lilmont

2023-12-30 13:30 UTC, lilmont commented on sources/Niloo Mont/MicroWebFramework/EncodingService.cs
> +        Encoding.UTF8.GetBytes(input+"\n");
Sure. How can I make the content more readable?

2023-12-30 13:30 UTC, lilmont commented on sources/Niloo Mont/MicroWebFramework/AuthenticationPipe.cs
> +        context.Response.OutputStream.Write(
Where should I write?

2023-12-30 13:31 UTC, lilmont commented on sources/Niloo Mont/README.md
Thanks for the feedback <3

2023-12-30 23:11 UTC, thisisnabi commented on sources/Niloo Mont/MicroWebFramework/AuthenticationPipe.cs
> +        context.Response.OutputStream.Write(
It's  log Nilofar! just write your action result into the response.

serialize action response and write into the response.

2023-12-30 23:20 UTC, thisisnabi commented on sources/Niloo Mont/MicroWebFramework/ProductsController.cs
> +            _httpContext.Response.OutputStream.Write(
You can move the writing into the response to another place. maybe `EndpointPipe`

In The ASP.NET, It handle in the ResultFilters :)

The advantage of this is that you have performed an action globally.

2023-12-30 23:25 UTC, thisisnabi commented on sources/Niloo Mont/MicroWebFramework/EncodingService.cs
> +        Encoding.UTF8.GetBytes(input+"\n");
You shouldn't have to do extra work in writing (serializing )the response, API developer is responsible for providing readable output. Currently you are SDK developer!

2023-12-31 00:09 UTC, thisisnabi commented on sources/Niloo Mont/README.md
I did not catch.
do you need more feedback? 

I look for the correct approach in the review.
The principle to choosing change for me is `So what?`.

2023-12-31 06:49 UTC, lilmont commented on sources/Niloo Mont/MicroWebFramework/AuthenticationPipe.cs
> +        context.Response.OutputStream.Write(
You're right. Thanks. I fixed it.

2023-12-31 06:53 UTC, lilmont commented on sources/Niloo Mont/README.md
No, I was just thanking :). This (<3) is the sign for the heart sticker.

2023-12-31 06:58 UTC, thisisnabi approved these changes

2023-12-31 06:58 UTC, merged