Feat/zahra liaghatmand
devblogs-ir/MicroWebFramework pull request #7
Opened 2023-12-30 17:52 UTC by liaghatmand

I commited this project for multiple controllers and actions.
To test it you can use these addresses:

http://localhost:4545/
http://localhost:4545/Products/GetUserById/3
http://localhost:4545/Products/GetAll/
http://localhost:4545/Orders/GetAll

I also Handled all the exceptions that may occur regarding the mistakes in writing the addresses.

2023-12-31 10:26 UTC, mohammadKarimi requested changes

2023-12-31 10:26 UTC, mohammadKarimi commented on sources/ZahraLiaghatmand/Controllers/HomeController.cs
> +namespace PipelineDesignPattern.Controllers
again File scoped namespace.

2023-12-31 10:26 UTC, mohammadKarimi commented on sources/ZahraLiaghatmand/Controllers/HomeController.cs
> +        private readonly HttpContext _context;
DRY.
please move it into your base controller.

2023-12-31 10:26 UTC, mohammadKarimi commented on sources/ZahraLiaghatmand/Exceptions/IPBanException.cs
> +    public IPBanException(string ip) : base(message: string.Format(ExceptionMessage, ip)) { }
please use string interpolation instead of string.format().

2023-12-31 10:26 UTC, mohammadKarimi commented on sources/ZahraLiaghatmand/Exceptions/IPBanException.cs
> +    private const string ExceptionMessage = "Your IP `{0}`  has been blocked.";
naming convention,. 

private field must be started with _

2023-12-31 10:26 UTC, mohammadKarimi commented on sources/ZahraLiaghatmand/Framework.cs
> +        public PipelineBuilder AddPipe<TType>()
you should limit TType with where keyword.

2023-12-31 10:26 UTC, mohammadKarimi commented on sources/ZahraLiaghatmand/Framework.cs
> +            var currentPipe = (Pipe)Activator.CreateInstance(_pipes[_pipes.Count - 1], null);
instead of using count - 1, please use ^1 (Range and Index )

2023-12-31 10:26 UTC, mohammadKarimi commented on sources/ZahraLiaghatmand/Framework.cs
> +
remove useless line break.

2023-12-31 10:26 UTC, mohammadKarimi commented on sources/ZahraLiaghatmand/Pipes/AuthenticationPipe.cs
> +namespace PipelineDesignPattern.Pipes
File scoped namespace.

`namespace PipelineDesignPattern.Pipes;`

2023-12-31 10:26 UTC, mohammadKarimi commented on sources/ZahraLiaghatmand/Pipes/AuthenticationPipe.cs
> +        Action<HttpContext> _next;
move this filed into base class. 
DRY.

2023-12-31 10:26 UTC, mohammadKarimi commented on sources/ZahraLiaghatmand/Pipes/AuthenticationPipe.cs
> +            if (_next != null)
is not.

2023-12-31 14:00 UTC, liaghatmand commented on sources/ZahraLiaghatmand/Controllers/HomeController.cs
> +namespace PipelineDesignPattern.Controllers
all the classes were checked and corrected

2024-01-01 07:39 UTC, mohammadKarimi approved these changes

2024-01-01 07:39 UTC, mohammadKarimi commented on sources/ZahraLiaghatmand/Controllers/NonController.cs
> +        if (this._context.Url.Split('/')[1] == "favicon.ico") {
is

magic string.

2024-01-01 07:39 UTC, mohammadKarimi commented on sources/ZahraLiaghatmand/Controllers/OrdersController.cs
> +    public OrdersController(HttpContext context)
you should pas this context to parent. 
what happens if you forget to set _context = context ??

2024-01-01 07:39 UTC, merged