Feat/hamidreza rahmani
devblogs-ir/MicroWebFramework pull request #8
Opened 2023-12-30 20:15 UTC by hamidreza-rahmani

In this exercise I tried to use Semaphore for handle Concurrent requests and objectPooling

2023-12-31 10:32 UTC, mohammadKarimi requested changes
your code is perfect. but I think you struggle in overthinking and needless complexity. 
Be careful.

2023-12-31 10:32 UTC, mohammadKarimi commented on sources/hamidreza-rahmani/MicroWebFramework/ObjectPool.cs
> +public class ObjectPool<T>
why you are using ObjectPool?

2023-12-31 10:32 UTC, mohammadKarimi commented on sources/hamidreza-rahmani/MicroWebFramework/Program.cs
> +var semaphore = new SemaphoreSlim(10, 10);
needless complexity.

2023-12-31 10:32 UTC, mohammadKarimi commented on sources/hamidreza-rahmani/MicroWebFramework/pipeline/PiplineBuilder.cs
> +        var currentPipe = (Pipe)Activator.CreateInstance(_pips[^1], null)!;
range and index 👍

2023-12-31 10:32 UTC, mohammadKarimi commented on sources/hamidreza-rahmani/MicroWebFramework/pipeline/PiplineBuilder.cs
> +    public PiplineBuilder Add<TType>()
please filter TType with where keyword.

2023-12-31 21:13 UTC, hamidreza-rahmani commented on sources/hamidreza-rahmani/MicroWebFramework/ObjectPool.cs
> +public class ObjectPool<T>
You are right I will try to fix this issue about needless complexity

2024-01-01 07:42 UTC, mohammadKarimi approved these changes

2024-01-01 07:42 UTC, merged